### ISSUE TITLE
This script is awesome 

### ISSUE THREAD

**Issue by teavanist** [readonlymaio/mm_id_rsa_bruteforce#1]
I had been trying to learn cracking of SSH private keys on the new Kali 2020. I had been at it for almost 2 days now and that's when I came to know that its a bug and saw your post on  stackexchange. Your script ran and cracked the passphrase in less than 10 seconds! Thanks a lot! I didnt find a way to reach out to you hence sending this as an issue :-)

**Comment by readonlymaio** [comment]
Hi Teavanist, thank you. The same happened to me: I was stuck with the issue of JTR on Kali and decided to work-around it by myself. :)
